//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONECTOR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control_Acceso
    {
        public int ID_Usuario { get; set; }
        public string Nombre_Usuario { get; set; }
        public string Contrasena { get; set; }
        public string Rol { get; set; }
        public Nullable<System.DateTime> Ultimo_Acceso { get; set; }
        public string Estado_Cuenta { get; set; }
    }
}
