//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONECTOR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int ID_Pago { get; set; }
        public Nullable<int> ID_Credito { get; set; }
        public Nullable<System.DateTime> Fecha_Pago { get; set; }
        public Nullable<decimal> Monto_Pago { get; set; }
        public string Metodo_Pago { get; set; }
        public string Estado_Pago { get; set; }
    }
}
